name: Haskell CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update package list
      run: cabal update
    - name: Install dependencies
      run: cabal install --only-dependencies
    - name: Build
      run: |
        cabal configure
        cabal build
